### ISSUE TITLE
Notes with ties are played twice

### ISSUE THREAD

**Issue by gaelcaradec** [jennyxing27/Verovio-Midi-Sync#1]
Hello Jennyxing,

Well done for the module, but I have encountered a problem with it and would like to share it with you.
The problem is that if two notes are linked by a tie, each of them is played in the midi instead of only the first one which should then normally be prolonged by the length of the second one.

Thanks,
Gael

**Comment by gaelcaradec** [comment]
I was refering to identical notes off course.

**Comment by gaelcaradec** [comment]
Hello,

I have seen in the verovio trunk that the issue had been already reported, so I'll just close it here.

Thanks,
Gael

**Comment by jennyxing** [comment]
ah great. I am currently no longer actively developing for Verovio, so please direct all issues to the develop-midi branch of the Verovio repository.

**Comment by lpugin** [comment]
This issue was actually already reported https://github.com/rism-ch/verovio/issues/196
